scheme: in run script, compute paths portably and on demand
https://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then

diff --git a/impls/scheme/run b/impls/scheme/run
--- a/impls/scheme/run
+++ b/impls/scheme/run
@@ -2,24 +2,28 @@
 basedir=$(dirname $0)
 step=${STEP:-stepA_mal}
 
-if [[ -e /usr/share/kawa/lib/kawa.jar ]]; then
-    kawa=/usr/share/kawa/lib/kawa.jar
-elif [[ -e /usr/local/share/kawa/lib/kawa.jar ]]; then
-    kawa=/usr/local/share/kawa/lib/kawa.jar
-fi
-
-if [[ $(which sash 2>/dev/null) ]]; then
-    sagittarius=sash
-elif [[ $(which sagittarius 2>/dev/null) ]]; then
-    sagittarius=sagittarius
-fi
-
 case ${scheme_MODE:-chibi} in
     chibi)       exec chibi-scheme -I$basedir $basedir/$step.scm      "${@}" ;;
-    kawa)        exec java -cp $kawa:$basedir/out $step               "${@}" ;;
+    kawa)        if [ -e /usr/share/kawa/lib/kawa.jar ]; then
+                     kawa=/usr/share/kawa/lib/kawa.jar
+                  elif [ -e /usr/local/share/kawa/lib/kawa.jar ]; then
+                     kawa=/usr/local/share/kawa/lib/kawa.jar
+                 else
+                     echo >&2 'Failed to find kawa.jar.'
+                     exit 1
+                 fi
+                 exec java -cp $kawa:$basedir/out $step               "${@}" ;;
     gauche)      exec gosh -I$basedir $basedir/$step.scm              "${@}" ;;
     chicken)     CHICKEN_REPOSITORY=$basedir/eggs exec $basedir/$step "${@}" ;;
-    sagittarius) exec $sagittarius -n -L$basedir $basedir/$step.scm   "${@}" ;;
+    sagittarius) if command -v sash >/dev/null 2>&1; then
+                     sagittarius=sash
+                 elif command -v sagittarius >/dev/null 2>&1; then
+                     sagittarius=sagittarius
+                 else
+                     echo >&2 'Failed to find sash or sagittarius.'
+                     exit 1
+                 fi
+                 exec $sagittarius -n -L$basedir $basedir/$step.scm   "${@}" ;;
     cyclone)     exec $basedir/$step                                  "${@}" ;;
     foment)      exec foment $basedir/$step.scm                       "${@}" ;;
     *) echo "Invalid scheme_MODE: ${scheme_MODE}"; exit 2 ;;
