run scripts: improve style

diff --git a/impls/basic/run b/impls/basic/run
--- a/impls/basic/run
+++ b/impls/basic/run
@@ -1,8 +1,12 @@
 #!/usr/bin/env bash
 cd $(dirname $0)
-(echo "(def! -*ARGS*- (list $(for a in "${@}"; do echo -n " \"${a}\""; done)))") > .args.mal
+{
+    printf '(def! -*ARGS*- (list'
+    [ $# = 0 ] || printf ' "%s"' "$@"
+    echo '))'
+} > .args.mal
 case ${basic_MODE:-cbm} in
-    cbm)    exec cbmbasic ${STEP:-stepA_mal}.bas "${@}" ;;
-    qbasic) exec ./${STEP:-stepA_mal} "${@}" ;;
-    *)      echo "Invalid basic_MODE: ${basic_MODE}"; exit 2 ;;
+    cbm)    exec cbmbasic ${STEP:-stepA_mal}.bas "$@" ;;
+    qbasic) exec ./${STEP:-stepA_mal} "$@" ;;
+    *)      echo "Invalid basic_MODE: $basic_MODE"; exit 2 ;;
 esac
diff --git a/impls/clojure/run b/impls/clojure/run
--- a/impls/clojure/run
+++ b/impls/clojure/run
@@ -1,8 +1,9 @@
 #!/usr/bin/env bash
-export PATH=$PATH:$(dirname $0)/node_modules/.bin
+export PATH="$PATH:$(dirname $0)/node_modules/.bin"
 STEP=${STEP:-stepA_mal}
-if [ "${clojure_MODE}" = "cljs" ]; then
-  exec lumo -c $(dirname $0)/src -m mal.${STEP//_/-} "${@}"
-else
-  exec java -jar $(dirname $0)/target/${STEP}.jar "${@}"
-fi
+case ${clojure_MODE:-clj} in
+    cljs) exec lumo -c $(dirname $0)/src -m mal.${STEP//_/-} "$@" ;;
+    clj)  exec java -jar $(dirname $0)/target/$STEP.jar "$@" ;;
+esac
+echo "Invalid clojure_MODE: $clojure_MODE"
+exit 1
diff --git a/impls/scheme/run b/impls/scheme/run
--- a/impls/scheme/run
+++ b/impls/scheme/run
@@ -3,7 +3,7 @@ basedir=$(dirname $0)
 step=${STEP:-stepA_mal}
 
 case ${scheme_MODE:-chibi} in
-    chibi)       exec chibi-scheme -I$basedir $basedir/$step.scm      "${@}" ;;
+    chibi)       exec chibi-scheme -I$basedir $basedir/$step.scm      "$@" ;;
     kawa)        if [ -e /usr/share/kawa/lib/kawa.jar ]; then
                      kawa=/usr/share/kawa/lib/kawa.jar
                   elif [ -e /usr/local/share/kawa/lib/kawa.jar ]; then
@@ -12,9 +12,9 @@ case ${scheme_MODE:-chibi} in
                      echo >&2 'Failed to find kawa.jar.'
                      exit 1
                  fi
-                 exec java -cp $kawa:$basedir/out $step               "${@}" ;;
-    gauche)      exec gosh -I$basedir $basedir/$step.scm              "${@}" ;;
-    chicken)     CHICKEN_REPOSITORY=$basedir/eggs exec $basedir/$step "${@}" ;;
+                 exec java -cp $kawa:$basedir/out $step               "$@" ;;
+    gauche)      exec gosh -I$basedir $basedir/$step.scm              "$@" ;;
+    chicken)     CHICKEN_REPOSITORY=$basedir/eggs exec $basedir/$step "$@" ;;
     sagittarius) if command -v sash >/dev/null 2>&1; then
                      sagittarius=sash
                  elif command -v sagittarius >/dev/null 2>&1; then
@@ -23,8 +23,8 @@ case ${scheme_MODE:-chibi} in
                      echo >&2 'Failed to find sash or sagittarius.'
                      exit 1
                  fi
-                 exec $sagittarius -n -L$basedir $basedir/$step.scm   "${@}" ;;
-    cyclone)     exec $basedir/$step                                  "${@}" ;;
-    foment)      exec foment $basedir/$step.scm                       "${@}" ;;
-    *) echo "Invalid scheme_MODE: ${scheme_MODE}"; exit 2 ;;
+                 exec $sagittarius -n -L$basedir $basedir/$step.scm   "$@" ;;
+    cyclone)     exec $basedir/$step                                  "$@" ;;
+    foment)      exec foment $basedir/$step.scm                       "$@" ;;
+    *) echo "Invalid scheme_MODE: $scheme_MODE"; exit 2 ;;
 esac
